import type { ImageMetadata } from "astro";
import blob from "../assets/gallery/blob.png";
import bottle from "../assets/gallery/bottle.png";
import city from "../assets/gallery/city.png";
import coffee from "../assets/gallery/coffee.png";
import icon from "../assets/gallery/icon.png";
import illustration from "../assets/gallery/illustration.png";
import mascot from "../assets/gallery/mascot.png";
import portrait from "../assets/gallery/portrait.png";

export type GalleryItem = {
	id: string;
	title: string;
	/** The exact prompt passed to Ploof. */
	prompt: string;
	model: string;
	command: string;
	image: ImageMetadata;
	alt: string;
	/** layout span hint */
	span?: "wide" | "tall";
};

/**
 * Every image below was generated by Ploof from the prompt shown, using the
 * manifest in `src/assets/gallery.manifest.yaml` (`ploof run gallery.yaml`).
 */
export const GALLERY: GalleryItem[] = [
	{
		id: "mascot",
		title: "Brand mascot",
		prompt:
			"Adorable 3D character of a fluffy white cloud with a cheerful face and tiny arms holding a small glowing retro computer terminal, floating above soft pastel clouds, lavender and peach gradient background, gentle sparkles, octane render.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --out mascot.png',
		image: mascot,
		alt: "A cute fluffy cloud character holding a retro computer terminal",
	},
	{
		id: "city",
		title: "Miniature city",
		prompt:
			"Wide cinematic tilt-shift photograph of a miniature paper city at blue hour, tiny warm glowing windows, soft fog drifting between paper skyscrapers, dreamy shallow depth of field.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --size 1536x1024 --out city.png',
		image: city,
		alt: "Tilt-shift miniature city at blue hour with glowing windows",
		span: "wide",
	},
	{
		id: "bottle",
		title: "Product photo",
		prompt:
			"Studio product photograph of a matte black insulated water bottle on white marble, soft natural daylight, subtle reflections, premium minimal e-commerce look, shot on 50mm.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --quality high --out bottle.png',
		image: bottle,
		alt: "Matte black water bottle on white marble, studio product photo",
	},
	{
		id: "portrait",
		title: "Editorial portrait",
		prompt:
			"Editorial portrait of a woman with freckles, dramatic warm side lighting, soft film grain, muted earthy tones, shallow depth of field, shot on 85mm.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --size 1024x1536 --out portrait.png',
		image: portrait,
		alt: "Editorial portrait of a woman with dramatic side lighting",
		span: "tall",
	},
	{
		id: "icon",
		title: "App icon",
		prompt:
			"3D isometric app icon of a friendly robot mascot made of soft matte clay, pastel lilac and mint, rounded squircle, subtle studio shadow, clean light background.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --out icon.png',
		image: icon,
		alt: "Soft clay 3D robot app icon in pastel colors",
	},
	{
		id: "illustration",
		title: "Vector illustration",
		prompt:
			"Flat vector illustration of a happy developer at a desk surrounded by floating UI panels and sparkles, soft pastel palette, clean rounded shapes, friendly modern tech brand style.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --size 1536x1024 --out dev.png',
		image: illustration,
		alt: "Flat vector illustration of a developer with floating UI panels",
		span: "wide",
	},
	{
		id: "coffee",
		title: "Food flat lay",
		prompt:
			"Overhead flat lay photograph of a flat white coffee with latte art and a flaky croissant on a natural linen tablecloth, soft morning light, minimal styling, warm tones.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --out coffee.png',
		image: coffee,
		alt: "Overhead photo of a flat white coffee and a croissant",
	},
	{
		id: "blob",
		title: "3D abstract",
		prompt:
			"Abstract glossy 3D gradient blob, smooth liquid iridescent surface, lavender to peach, soft studio lighting on a clean off-white background, minimal, high detail.",
		model: "gpt-image-2",
		command: 'ploof image generate --prompt "…" --out blob.png',
		image: blob,
		alt: "Glossy iridescent 3D blob in lavender and peach",
	},
];
