function markdown(lines: string[]): string {
	return `${lines.join("\n").trim()}\n`;
}

const output = markdown([
	"# Generate assets with the ploof CLI",
	"",
	"Ploof is an AI asset generation CLI. Use it when a task needs generated or edited images or videos, generated or processed audio, batch asset creation, provider authentication, media context inputs, or reusable generation manifests.",
	"",
	"Package name: `@miketromba/ploof`. Command name: `ploof`. Supported today: OpenAI image generation/editing, OpenAI video generation/editing/extensions/downloads/characters, and OpenAI audio generation/transcription/translation. OpenAI image variations are implemented through the legacy DALL-E 2 endpoint when the authenticated project has access.",
	"",
	"## Core workflow",
	"",
	"1. Run `ploof whoami openai`. If unauthenticated, ask the user to run `ploof login openai` or provide `PLOOF_OPENAI_API_KEY` in their shell.",
	"2. For one image asset, use `ploof image generate` or `ploof image edit` with an explicit `--out` path.",
	"3. For one video asset, use `ploof video generate --out <path>` so Ploof waits for completion and downloads the MP4.",
	"4. For one audio asset, use `ploof audio generate --out <path>` for TTS, or `ploof audio transcribe/translate --audio <path> --out <path>` for processing.",
	"5. For multiple assets, dependencies, or parallel work, write a YAML manifest and run `ploof run <manifest.yaml>`.",
	"6. Use `--output json` for commands another tool or agent must parse. Use `--output jsonl` for batch streams.",
	"7. After a command completes, verify every path in `outputs` exists before telling the user generation succeeded.",
	"",
	"## Authentication",
	"",
	"```bash",
	"ploof login openai --api-key <key>",
	"ploof whoami openai",
	"ploof profiles openai",
	"```",
	"",
	"There is no `ploof auth` namespace. The authentication commands are top-level: `login`, `whoami`, `profiles`, and `logout`.",
	"",
	"Environment variables override stored credentials:",
	"",
	"```bash",
	"PLOOF_OPENAI_API_KEY=...",
	"OPENAI_API_KEY=...",
	"```",
	"",
	"Use `--profile <name>` on `login`, `whoami`, `image ...`, `video ...`, and manifest tasks when the user has multiple OpenAI credentials. Never print or store secrets in generated project files.",
	"",
	"## Image generation",
	"",
	"```bash",
	"ploof image generate \\",
	"  --provider openai \\",
	'  --prompt "Studio product photo" \\',
	"  --out assets/hero.png \\",
	"  --model gpt-image-2 \\",
	"  --size 1024x1024 \\",
	"  --quality high \\",
	"  --format png \\",
	"  --output json",
	"```",
	"",
	"OpenAI image generation and editing default to `gpt-image-2` when `--model` is omitted.",
	"",
	"Important: `--format png` controls the generated asset format. `--output json` controls CLI output formatting.",
	"",
	"First-class OpenAI image flags:",
	"",
	"- `--model <model>`: for example `gpt-image-2`.",
	"- `--size <size>`: provider size such as `1024x1024`.",
	"- `--quality <quality>`: provider quality such as `low`, `medium`, or `high` when supported.",
	"- `--format <format>` or `--output-format <format>`: provider image format, usually `png`, `jpeg`, or `webp` when supported.",
	"- `--background <value>`, `--moderation <value>`, `--n <count>`, `--output-compression <number>`, `--partial-images <number>`, `--response-format <format>`, `--style <style>`, `--user <id>`, `--stream`.",
	"- `--param key=value`: pass one provider-specific parameter. Nested keys work, such as `--param extra.foo=bar`.",
	"- `--json '{...}'`: merge a provider-specific JSON object into the request. Explicit first-class flags override overlapping JSON keys.",
	"",
	"Use `--quality low` for cheap smoke tests. Use the user's requested quality and size for final assets.",
	"",
	"## Image editing and context images",
	"",
	"```bash",
	"ploof image edit \\",
	"  --provider openai \\",
	"  --image input.png \\",
	"  --image reference.png \\",
	"  --mask mask.png \\",
	'  --prompt "Replace the background" \\',
	"  --out assets/edited.png \\",
	"  --model gpt-image-2 \\",
	"  --format png \\",
	"  --output json",
	"```",
	"",
	"Pass every source image the provider should see with repeated `--image`. Use `--mask` only when the provider/model supports masked edits. Edit also supports `--input-fidelity <value>`.",
	"",
	"Input assets can be local paths, `http://` or `https://` URLs, or `-` for stdin. Ploof infers common image MIME types from file extensions and preserves generated files locally.",
	"",
	"## Image variations",
	"",
	"```bash",
	"ploof image variation \\",
	"  --provider openai \\",
	"  --image input.png \\",
	"  --out assets/variation.png \\",
	"  --size 1024x1024 \\",
	"  --output json",
	"```",
	"",
	"OpenAI variations default to `dall-e-2`, because OpenAI's legacy variations endpoint currently only supports `dall-e-2`. If OpenAI returns a 404, use `ploof image edit` for image-to-image workflows or try a profile/project with DALL-E 2 variation access. `ploof image variations` is an alias.",
	"",
	"## Video generation",
	"",
	"```bash",
	"ploof video generate \\",
	"  --provider openai \\",
	'  --prompt "Wide tracking shot of a paper city at blue hour" \\',
	"  --model sora-2 \\",
	"  --size 1280x720 \\",
	"  --seconds 4 \\",
	"  --out assets/clip.mp4 \\",
	"  --output json",
	"```",
	"",
	"OpenAI video generation defaults to `sora-2` when `--model` is omitted. Video jobs are asynchronous. Passing `--out` or `--download` makes Ploof wait for a terminal status and download the requested asset.",
	"",
	"First-class OpenAI video flags:",
	"",
	"- `--model <model>`: for example `sora-2` or `sora-2-pro`.",
	"- `--size <size>`: provider size such as `1280x720`.",
	"- `--seconds <seconds>`: clip or extension duration.",
	"- `--input-reference <path-or-url-or-file-id>`, `--input-reference-file-id <id>`, or `--input-reference-url <url>`: image reference for the first frame.",
	"- `--character <id>`: reusable character id; repeat for multiple characters and mention the character name in the prompt.",
	"- `--wait`, `--download`, `--variant video|thumbnail|spritesheet`, `--poll-interval <seconds>`, `--timeout <seconds>`.",
	"- `--param key=value` and `--json '{...}'` work for provider-specific video settings.",
	"",
	"## Video editing, extension, and library",
	"",
	"```bash",
	"ploof video edit \\",
	"  --video-id video_abc123 \\",
	'  --prompt "Shift the palette to teal and rust" \\',
	"  --out assets/edit.mp4 \\",
	"  --output json",
	"",
	"ploof video extend \\",
	"  --video-id video_abc123 \\",
	'  --prompt "Continue as the camera rises over the rooftops" \\',
	"  --seconds 4 \\",
	"  --out assets/extended.mp4 \\",
	"  --output json",
	"",
	"ploof video download video_abc123 --variant thumbnail --out assets/thumb.webp --output json",
	"ploof video status video_abc123 --output json",
	"ploof video list --limit 20 --output json",
	"```",
	"",
	"Video edits accept `--video-id <id>` for completed OpenAI videos or `--video <path>` for uploaded source videos when the authenticated project is eligible. Extensions accept `--video-id` or `--video`, plus `--seconds`.",
	"",
	"Reusable characters:",
	"",
	"```bash",
	"ploof video character create --name Mossy --video character.mp4 --output json",
	"ploof video character get char_abc123 --output json",
	"```",
	"",
	"## Audio generation and processing",
	"",
	"```bash",
	"ploof audio generate \\",
	"  --provider openai \\",
	'  --text "Short narration for the generated asset." \\',
	"  --model gpt-4o-mini-tts \\",
	"  --voice alloy \\",
	"  --format mp3 \\",
	"  --out assets/narration.mp3 \\",
	"  --output json",
	"",
	"ploof audio transcribe \\",
	"  --audio assets/narration.mp3 \\",
	"  --model gpt-4o-mini-transcribe \\",
	"  --out assets/transcript.json \\",
	"  --output json",
	"",
	"ploof audio translate \\",
	"  --audio assets/spanish.mp3 \\",
	"  --model whisper-1 \\",
	"  --format text \\",
	"  --out assets/translation.txt \\",
	"  --output json",
	"```",
	"",
	"OpenAI audio generation defaults to `gpt-4o-mini-tts`, `alloy`, and `mp3`. OpenAI transcription defaults to `gpt-4o-mini-transcribe` with JSON output. OpenAI translation defaults to `whisper-1` with JSON output.",
	"",
	"First-class audio generation flags:",
	"",
	"- `--model <model>`, `--voice <voice>`, `--voice-id <id>`, `--instructions <text>`, `--format <format>`, `--speed <number>`.",
	"- `--format` or `--response-format` can be `mp3`, `opus`, `aac`, `flac`, `wav`, or `pcm` when supported.",
	"- `--param key=value` and `--json '{...}'` work for provider-specific audio settings.",
	"- Ploof writes complete static audio files. Do not use streaming transport settings such as OpenAI `stream_format=sse`.",
	"",
	"First-class audio processing flags:",
	"",
	"- Transcribe: `--model`, `--language`, `--prompt`, `--format`, `--temperature`, `--include`, `--timestamp-granularity`, `--chunking-strategy`, `--known-speaker-name`, `--known-speaker-reference`.",
	"- Translate: `--model`, `--prompt`, `--format`, `--temperature`.",
	"- Text outputs can be JSON, plain text, SRT, or VTT depending on provider/model support. Do not use streaming transport settings such as OpenAI `stream=true`.",
	"",
	"## Outputs and verification",
	"",
	"`--out <path>` can be a file path or directory. When generating multiple images with `--n`, a file path is expanded with `-1`, `-2`, etc. Video downloads use `.mp4`, thumbnails use `.webp`, and spritesheets use `.jpg`. If `--out` is omitted for image generation, Ploof writes in the current directory using default names like `image.png` or `edited-image.png`.",
	"",
	"Default sidecar metadata is enabled. For each output file, Ploof writes `<output>.json` with the operation, prompt, params, outputs, provider metadata, and timestamp.",
	"",
	"Parseable result shape:",
	"",
	"```json",
	"{",
	'  "kind": "video.generate",',
	'  "provider": "openai",',
	'  "profile": "default",',
	'  "outputs": ["assets/clip.mp4"],',
	'  "metadata": { "video": { "id": "video_...", "status": "completed" } }',
	"}",
	"```",
	"",
	"Useful global output flags:",
	"",
	"- `--output json|jsonl|compact|table`: choose CLI output format.",
	"- `--fields outputs,metadata.usage.total_tokens`: select fields for parseable outputs.",
	"- `--detail`, `--quiet`, `--no-color`, `--verbose`.",
	"",
	"## Batch manifests",
	"",
	"```yaml",
	"version: 1",
	"parallel: 4",
	"tasks:",
	"  - id: base",
	"    kind: image.generate",
	"    provider: openai",
	"    profile: default",
	'    prompt: "Studio product photo"',
	"    output: assets/base.png",
	"    params:",
	"      model: gpt-image-2",
	"      size: 1024x1024",
	"      quality: high",
	"      output_format: png",
	"",
	"  - id: edit",
	"    kind: image.edit",
	"    provider: openai",
	"    needs: [base]",
	"    inputs:",
	"      images:",
	"        - task: base",
	"        - source: ./reference.png",
	"      mask:",
	"        source: ./mask.png",
	'    prompt: "Add a premium background"',
	"    output: assets/final.png",
	"    params:",
	"      model: gpt-image-2",
	"      size: 1024x1024",
	"",
	"  - id: variation",
	"    kind: image.variation",
	"    provider: openai",
	"    needs: [base]",
	"    inputs:",
	"      images:",
	"        - task: base",
	"    output: assets/variation.png",
	"",
	"  - id: clip",
	"    kind: video.generate",
	"    provider: openai",
	'    prompt: "Slow dolly shot through a miniature paper city"',
	"    output: assets/clip.mp4",
	"    wait: true",
	"    download: true",
	"    params:",
	"      model: sora-2",
	"      size: 1280x720",
	"      seconds: '4'",
	"",
	"  - id: narration",
	"    kind: audio.generate",
	"    provider: openai",
	'    text: "Short narration for the generated clip."',
	"    output: assets/narration.mp3",
	"    params:",
	"      model: gpt-4o-mini-tts",
	"      voice: alloy",
	"      response_format: mp3",
	"",
	"  - id: transcript",
	"    kind: audio.transcribe",
	"    provider: openai",
	"    needs: [narration]",
	"    inputs:",
	"      audio:",
	"        task: narration",
	"    output: assets/transcript.json",
	"    params:",
	"      model: gpt-4o-mini-transcribe",
	"```",
	"",
	"Run it with:",
	"",
	"```bash",
	"ploof run assets.yaml --parallel 4 --output json",
	"```",
	"",
	"Manifest notes:",
	"",
	"- `version: 1`, `parallel`, and `tasks` are supported.",
	"- Task kinds include `image.generate`, `image.edit`, `image.variation`, `video.generate`, `video.edit`, `video.extend`, `video.remix`, `video.status`, `video.download`, `video.list`, `video.delete`, `video.character.create`, `video.character.get`, `audio.generate`, `audio.transcribe`, and `audio.translate`.",
	"- Task fields: `id`, `kind`, `provider`, `profile`, `needs`, `prompt`, `text`, `output`, `params`, `sidecar`, `inputs`, `videoId`, `characterId`, `name`, `wait`, `download`, `variants`, `pollIntervalMs`, and `timeoutMs`.",
	"- Relative paths are resolved from the manifest file location.",
	"- `inputs.images` accepts strings, `{ source }`, or `{ task }`. `{ task: base }` uses the first output from that completed task.",
	"- `inputs.video`, `inputs.videos`, and `inputs.inputReference` use the same input reference shape.",
	"- `inputs.audio` uses the same input reference shape for transcription and translation.",
	"- Run `ploof run assets.yaml --dry-run --output json` before expensive batches.",
	"",
	"## Configuration",
	"",
	"```bash",
	"ploof config list",
	"ploof config set output json",
	"ploof config set defaultParallel 4",
	"ploof config set sidecar true",
	"ploof config reset",
	"```",
	"",
	"Config is stored at `~/.ploof/config.json`. Credentials are stored separately at `~/.ploof/credentials.json`.",
	"",
	"## Agent guidance",
	"",
	"- Prefer exact user-provided prompts, dimensions, source images, and output paths. Ask only when a missing choice would change the intended asset.",
	"- Keep prompts and params explicit in commands or manifests.",
	"- Use deterministic output paths, usually under the user's requested asset directory or a temp directory for tests.",
	"- Use manifests for parallel generation, dependency chains, or more than one related asset.",
	"- Keep `--parallel` modest unless the user requests volume; generation costs money and provider rate limits may apply.",
	"- Report generated file paths and any relevant metadata such as model and token usage.",
	"- Do not claim assets were generated unless the command completed successfully and output files exist.",
	"- If a command fails, report the command goal, the error, and the next concrete fix. Do not fabricate assets.",
	"- Run `ploof <command> --help` when a detail is unclear; prefer the installed CLI help over memory.",
]);

function usage(): string {
	return markdown([
		"Usage: ploof learn [options]",
		"",
		"Print AI-agent instructions for using the installed ploof CLI.",
		"",
		"Options:",
		"  --help, -h  Show this help",
		"",
		"Examples:",
		"  ploof learn",
	]);
}

export function getLearnOutput(args: string[] = []): string {
	if (args.includes("--help") || args.includes("-h")) return usage();
	const unknownArg = args.find((arg) => arg.trim() !== "");
	if (unknownArg) {
		throw new Error(`Unknown learn argument: ${unknownArg}\n\n${usage()}`);
	}
	return output;
}
