function markdown(lines: string[]): string {
	return `${lines.join("\n").trim()}\n`;
}

const output = markdown([
	"# Generate assets with the ploof CLI",
	"",
	"Ploof is an AI asset generation CLI. Use it when a task needs generated or edited images, batch asset creation, provider authentication, or reusable asset generation manifests.",
	"",
	"## Core workflow",
	"",
	"1. Check auth with `ploof whoami openai`.",
	"2. Generate one-off images with `ploof image generate`.",
	"3. Edit/contextualize images with `ploof image edit --image <path>` and optional `--mask <path>`.",
	"4. Use `ploof run <manifest.yaml>` for multi-asset or dependency-aware work.",
	"5. Prefer `--output json` or `--output jsonl` when another tool or agent needs to parse results.",
	"",
	"## Authentication",
	"",
	"```bash",
	"ploof login openai --api-key <key>",
	"ploof whoami openai",
	"ploof profiles openai",
	"```",
	"",
	"Environment variables override stored credentials:",
	"",
	"```bash",
	"PLOOF_OPENAI_API_KEY=...",
	"OPENAI_API_KEY=...",
	"```",
	"",
	"## Image generation",
	"",
	"```bash",
	"ploof image generate \\",
	"  --provider openai \\",
	'  --prompt "Studio product photo" \\',
	"  --out assets/hero.png \\",
	"  --model gpt-image-1 \\",
	"  --size 1024x1024 \\",
	"  --quality high \\",
	"  --output json",
	"```",
	"",
	"Use `--param key=value` for provider-specific fields that do not have first-class flags. Use `--json '{...}'` for larger provider payloads.",
	"",
	"## Image editing and context images",
	"",
	"```bash",
	"ploof image edit \\",
	"  --provider openai \\",
	"  --image input.png \\",
	"  --image reference.png \\",
	"  --mask mask.png \\",
	'  --prompt "Replace the background" \\',
	"  --out assets/edited.png \\",
	"  --output json",
	"```",
	"",
	"Pass every source image the provider should see with repeated `--image`. Use `--mask` only when the provider/model supports masked edits.",
	"",
	"## Batch manifests",
	"",
	"```yaml",
	"version: 1",
	"parallel: 4",
	"tasks:",
	"  - id: base",
	"    kind: image.generate",
	"    provider: openai",
	'    prompt: "Studio product photo"',
	"    output: assets/base.png",
	"",
	"  - id: edit",
	"    kind: image.edit",
	"    provider: openai",
	"    needs: [base]",
	"    inputs:",
	"      images:",
	"        - task: base",
	"      mask: ./mask.png",
	'    prompt: "Add a premium background"',
	"    output: assets/final.png",
	"```",
	"",
	"Run it with:",
	"",
	"```bash",
	"ploof run assets.yaml --parallel 4 --output json",
	"```",
	"",
	"## Agent guidance",
	"",
	"- Keep prompts and params explicit in commands or manifests.",
	"- Use deterministic output paths so later steps can find generated files.",
	"- Use `--dry-run` on manifests before expensive runs.",
	"- Report generated file paths from the command output.",
	"- Do not claim assets were generated unless the command completed and output files exist.",
]);

function usage(): string {
	return markdown([
		"Usage: ploof learn [options]",
		"",
		"Print AI-agent instructions for using the installed ploof CLI.",
		"",
		"Options:",
		"  --help, -h  Show this help",
		"",
		"Examples:",
		"  ploof learn",
	]);
}

export function getLearnOutput(args: string[] = []): string {
	if (args.includes("--help") || args.includes("-h")) return usage();
	const unknownArg = args.find((arg) => arg.trim() !== "");
	if (unknownArg) {
		throw new Error(`Unknown learn argument: ${unknownArg}\n\n${usage()}`);
	}
	return output;
}
