function markdown(lines: string[]): string {
	return `${lines.join("\n").trim()}\n`;
}

const output = markdown([
	"# Generate assets with the ploof CLI",
	"",
	"Ploof is an AI asset generation CLI. Use it when a task needs generated or edited images, batch asset creation, provider authentication, image context inputs, or reusable generation manifests.",
	"",
	"Package name: `@miketromba/ploof`. Command name: `ploof`. Supported today: OpenAI image generation, image editing, and image variations.",
	"",
	"## Core workflow",
	"",
	"1. Run `ploof whoami openai`. If unauthenticated, ask the user to run `ploof login openai` or provide `PLOOF_OPENAI_API_KEY` in their shell.",
	"2. For one asset, use `ploof image generate` or `ploof image edit` with an explicit `--out` path.",
	"3. For multiple assets, dependencies, or parallel work, write a YAML manifest and run `ploof run <manifest.yaml>`.",
	"4. Use `--output json` for commands another tool or agent must parse. Use `--output jsonl` for batch streams.",
	"5. After a command completes, verify every path in `outputs` exists before telling the user generation succeeded.",
	"",
	"## Authentication",
	"",
	"```bash",
	"ploof login openai --api-key <key>",
	"ploof whoami openai",
	"ploof profiles openai",
	"```",
	"",
	"There is no `ploof auth` namespace. The authentication commands are top-level: `login`, `whoami`, `profiles`, and `logout`.",
	"",
	"Environment variables override stored credentials:",
	"",
	"```bash",
	"PLOOF_OPENAI_API_KEY=...",
	"OPENAI_API_KEY=...",
	"```",
	"",
	"Use `--profile <name>` on `login`, `whoami`, `image generate`, `image edit`, `image variation`, and manifest tasks when the user has multiple OpenAI credentials. Never print or store secrets in generated project files.",
	"",
	"## Image generation",
	"",
	"```bash",
	"ploof image generate \\",
	"  --provider openai \\",
	'  --prompt "Studio product photo" \\',
	"  --out assets/hero.png \\",
	"  --model gpt-image-2 \\",
	"  --size 1024x1024 \\",
	"  --quality high \\",
	"  --format png \\",
	"  --output json",
	"```",
	"",
	"OpenAI image generation and editing default to `gpt-image-2` when `--model` is omitted.",
	"",
	"Important: `--format png` controls the generated asset format. `--output json` controls CLI output formatting.",
	"",
	"First-class OpenAI image flags:",
	"",
	"- `--model <model>`: for example `gpt-image-2`.",
	"- `--size <size>`: provider size such as `1024x1024`.",
	"- `--quality <quality>`: provider quality such as `low`, `medium`, or `high` when supported.",
	"- `--format <format>` or `--output-format <format>`: provider image format, usually `png`, `jpeg`, or `webp` when supported.",
	"- `--background <value>`, `--moderation <value>`, `--n <count>`, `--output-compression <number>`, `--partial-images <number>`, `--response-format <format>`, `--style <style>`, `--user <id>`, `--stream`.",
	"- `--param key=value`: pass one provider-specific parameter. Nested keys work, such as `--param extra.foo=bar`.",
	"- `--json '{...}'`: merge a provider-specific JSON object into the request. Explicit first-class flags override overlapping JSON keys.",
	"",
	"Use `--quality low` for cheap smoke tests. Use the user's requested quality and size for final assets.",
	"",
	"## Image editing and context images",
	"",
	"```bash",
	"ploof image edit \\",
	"  --provider openai \\",
	"  --image input.png \\",
	"  --image reference.png \\",
	"  --mask mask.png \\",
	'  --prompt "Replace the background" \\',
	"  --out assets/edited.png \\",
	"  --model gpt-image-2 \\",
	"  --format png \\",
	"  --output json",
	"```",
	"",
	"Pass every source image the provider should see with repeated `--image`. Use `--mask` only when the provider/model supports masked edits. Edit also supports `--input-fidelity <value>`.",
	"",
	"Input assets can be local paths, `http://` or `https://` URLs, or `-` for stdin. Ploof infers common image MIME types from file extensions and preserves generated files locally.",
	"",
	"## Image variations",
	"",
	"```bash",
	"ploof image variation \\",
	"  --provider openai \\",
	"  --image input.png \\",
	"  --out assets/variation.png \\",
	"  --size 1024x1024 \\",
	"  --output json",
	"```",
	"",
	"OpenAI variations default to `dall-e-2`, because OpenAI's variations endpoint currently only supports `dall-e-2`. `ploof image variations` is an alias.",
	"",
	"## Outputs and verification",
	"",
	"`--out <path>` can be a file path or directory. When generating multiple images with `--n`, a file path is expanded with `-1`, `-2`, etc. If `--out` is omitted, Ploof writes in the current directory using default names like `image.png` or `edited-image.png`.",
	"",
	"Default sidecar metadata is enabled. For each output file, Ploof writes `<output>.json` with the operation, prompt, params, outputs, provider metadata, and timestamp.",
	"",
	"Parseable result shape:",
	"",
	"```json",
	"{",
	'  "kind": "image.generate",',
	'  "provider": "openai",',
	'  "profile": "default",',
	'  "outputs": ["assets/hero.png"],',
	'  "metadata": { "model": "gpt-image-2" }',
	"}",
	"```",
	"",
	"Useful global output flags:",
	"",
	"- `--output json|jsonl|compact|table`: choose CLI output format.",
	"- `--fields outputs,metadata.usage.total_tokens`: select fields for parseable outputs.",
	"- `--detail`, `--quiet`, `--no-color`, `--verbose`.",
	"",
	"## Batch manifests",
	"",
	"```yaml",
	"version: 1",
	"parallel: 4",
	"tasks:",
	"  - id: base",
	"    kind: image.generate",
	"    provider: openai",
	"    profile: default",
	'    prompt: "Studio product photo"',
	"    output: assets/base.png",
	"    params:",
	"      model: gpt-image-2",
	"      size: 1024x1024",
	"      quality: high",
	"      output_format: png",
	"",
	"  - id: edit",
	"    kind: image.edit",
	"    provider: openai",
	"    needs: [base]",
	"    inputs:",
	"      images:",
	"        - task: base",
	"        - source: ./reference.png",
	"      mask:",
	"        source: ./mask.png",
	'    prompt: "Add a premium background"',
	"    output: assets/final.png",
	"    params:",
	"      model: gpt-image-2",
	"      size: 1024x1024",
	"",
	"  - id: variation",
	"    kind: image.variation",
	"    provider: openai",
	"    needs: [base]",
	"    inputs:",
	"      images:",
	"        - task: base",
	"    output: assets/variation.png",
	"```",
	"",
	"Run it with:",
	"",
	"```bash",
	"ploof run assets.yaml --parallel 4 --output json",
	"```",
	"",
	"Manifest notes:",
	"",
	"- `version: 1`, `parallel`, and `tasks` are supported.",
	"- Task kinds are `image.generate`, `image.edit`, and `image.variation`.",
	"- Task fields: `id`, `kind`, `provider`, `profile`, `needs`, `prompt`, `output`, `params`, `sidecar`, `inputs`.",
	"- Relative paths are resolved from the manifest file location.",
	"- `inputs.images` accepts strings, `{ source }`, or `{ task }`. `{ task: base }` uses the first output from that completed task.",
	"- Run `ploof run assets.yaml --dry-run --output json` before expensive batches.",
	"",
	"## Configuration",
	"",
	"```bash",
	"ploof config list",
	"ploof config set output json",
	"ploof config set defaultParallel 4",
	"ploof config set sidecar true",
	"ploof config reset",
	"```",
	"",
	"Config is stored at `~/.ploof/config.json`. Credentials are stored separately at `~/.ploof/credentials.json`.",
	"",
	"## Agent guidance",
	"",
	"- Prefer exact user-provided prompts, dimensions, source images, and output paths. Ask only when a missing choice would change the intended asset.",
	"- Keep prompts and params explicit in commands or manifests.",
	"- Use deterministic output paths, usually under the user's requested asset directory or a temp directory for tests.",
	"- Use manifests for parallel generation, dependency chains, or more than one related asset.",
	"- Keep `--parallel` modest unless the user requests volume; generation costs money and provider rate limits may apply.",
	"- Report generated file paths and any relevant metadata such as model and token usage.",
	"- Do not claim assets were generated unless the command completed successfully and output files exist.",
	"- If a command fails, report the command goal, the error, and the next concrete fix. Do not fabricate assets.",
	"- Run `ploof <command> --help` when a detail is unclear; prefer the installed CLI help over memory.",
]);

function usage(): string {
	return markdown([
		"Usage: ploof learn [options]",
		"",
		"Print AI-agent instructions for using the installed ploof CLI.",
		"",
		"Options:",
		"  --help, -h  Show this help",
		"",
		"Examples:",
		"  ploof learn",
	]);
}

export function getLearnOutput(args: string[] = []): string {
	if (args.includes("--help") || args.includes("-h")) return usage();
	const unknownArg = args.find((arg) => arg.trim() !== "");
	if (unknownArg) {
		throw new Error(`Unknown learn argument: ${unknownArg}\n\n${usage()}`);
	}
	return output;
}
